#!/usr/bin/env ruby
require 'rubygems'
require 'jajah-reseller'

caller = JajahReseller::Caller.new(payingUserName,payingPassword)
caller.call(fromNumber, toNumbers,'BothNumbersAreVisible')

puts result.inspect